const CATEGORIES = [
  { id: "uredjivanje", label: "Uređivanje šuma", icon: "🗺️" },
  { id: "uzgajanje", label: "Uzgajanje šuma", icon: "🌱" },
  { id: "ekonomika", label: "Ekonomika šumarstva", icon: "💰" },
  { id: "iskoristavanje", label: "Iskorištavanje šuma", icon: "🪓" },
  { id: "dendrometrija", label: "Dendrometrija", icon: "📏" },
  { id: "mix", label: "Mix (sve kategorije)", icon: "🔀" },
];

const QUESTIONS = [
  // ---------- UREĐIVANJE ŠUMA ----------
  {
    category: "uredjivanje",
    q: "Šta je osnovni cilj uređivanja šuma?",
    a: [
      "Sječa svih stabala u kratkom roku",
      "Planiranje i regulisanje gospodarenja šumom radi trajnosti prinosa",
      "Prodaja šumskog zemljišta",
      "Uklanjanje divljači",
    ],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Kako se naziva osnovni planski dokument za gospodarenje šumom na nivou gospodarske jedinice?",
    a: ["Šumskoprivredna osnova", "Katastar nekretnina", "Urbanistički plan", "Geodetski elaborat"],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'gospodarska jedinica' u uređivanju šuma?",
    a: ["Pojedinačno stablo", "Teritorijalno-gospodarska cjelina za koju se izrađuje osnova gazdovanja", "Vrsta drveta", "Alat za sječu"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta predstavlja 'etat' u šumarstvu?",
    a: ["Ukupna površina šume", "Propisana (dozvoljena) količina drvne mase za sječu u određenom periodu", "Vrsta tla", "Naziv za mladu šumu"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Koji je cilj podjele šume na odjele i odsjeke?",
    a: ["Estetski razlozi", "Lakše planiranje, evidencija i gospodarenje šumom", "Sprečavanje rasta korova", "Obilježavanje granica država"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'ophodnja' (turnus) u uređivanju šuma?",
    a: ["Vremenski period za koji se šuma pomladi i doraste do sječive zrelosti", "Dnevna smjena šumskih radnika", "Godišnji odmor šumara", "Period čuvanja sjemena"],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Koji faktor NAJVIŠE određuje dužinu ophodnje?",
    a: ["Cijena goriva", "Vrsta drveta, stanište i cilj gospodarenja", "Broj zaposlenih u šumariji", "Udaljenost od grada"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'prirast' drvne mase?",
    a: ["Gubitak drvne mase usljed bolesti", "Povećanje zapremine drvne mase u određenom vremenskom periodu", "Broj posječenih stabala", "Vrsta gnojiva"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta znači princip 'trajnosti prinosa' u uređivanju šuma?",
    a: ["Sječa što više drveta u što kraćem roku", "Ravnomjerno i održivo korištenje šume tako da prinos ostane trajno moguć", "Zabrana svake sječe", "Sadnja samo brzorastućih vrsta"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta je funkcija Geografskog informacionog sistema (GIS) u uređivanju šuma?",
    a: ["Prodaja drvne građe", "Prikupljanje, analiza i prikaz prostornih podataka o šumi", "Zaštita od požara direktnim gašenjem", "Uzgoj sadnica"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'bonitet staništa' u uređivanju šuma?",
    a: ["Cijena zemljišta", "Ocjena proizvodne sposobnosti staništa za rast šume", "Broj vrsta životinja", "Nadmorska visina"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Koji dokument definiše dugoročne ciljeve gospodarenja šumama na nivou cijele države/regije?",
    a: ["Šumskoprivredna osnova", "Strategija/plan razvoja šumarstva", "Dnevni izvještaj šumara", "Faktura za drvo"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta je zadatak revizije šumskoprivredne osnove?",
    a: ["Prodaja šume", "Periodična provjera i usklađivanje plana gazdovanja sa stvarnim stanjem šume", "Sadnja cvijeća", "Mjerenje temperature zraka"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Šta znači pojam 'normalna šuma' u teoriji uređivanja šuma?",
    a: ["Šuma bez ijednog stabla", "Teorijski model šume s idealnom razdiobom starosnih razreda za trajni prinos", "Bolesna šuma", "Prašuma bez ljudskog uticaja"],
    correct: 1,
  },
  {
    category: "uredjivanje",
    q: "Koja metoda uređivanja šuma se zasniva na kontroli stanja sastojine i prirasta umjesto strogog plana sječa?",
    a: ["Metoda kontrole (kontrolna metoda)", "Metoda čiste sječe", "Metoda monokulture", "Metoda 'sve ili ništa'"],
    correct: 0,
  },

  // ---------- UZGAJANJE ŠUMA ----------
  {
    category: "uzgajanje",
    q: "Šta je zadatak uzgajanja šuma kao struke?",
    a: ["Prodaja drvne građe", "Njega, obnova i unapređenje šumskih sastojina", "Mjerenje visine stabala", "Izrada šumskih cesta"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'prirodno pomlađivanje' šume?",
    a: ["Obnova šume sadnjom sadnica iz rasadnika", "Obnova šume iz sjemena zrelih stabala bez sadnje", "Uvoz drveća iz drugih zemalja", "Sječa svih stabala"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'vještačko pomlađivanje'?",
    a: ["Obnova šume sadnjom sadnica ili sjetvom sjemena od strane čovjeka", "Prirodno nicanje sjemena", "Rast panjeva (izbojci)", "Rast iz korijena"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Kako se naziva obnova šume iz izbojaka iz panja ili korijena?",
    a: ["Sjemenska obnova", "Panjača (izdanačka šuma)", "Sadnja", "Kalemljenje"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je proreda (prorjeđivanje) sastojine?",
    a: ["Potpuno uklanjanje šume", "Uklanjanje dijela stabala radi boljeg rasta preostalih i kvalitetnijeg drveta", "Sadnja novih vrsta", "Zalijevanje šume"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Koja mjera njege se provodi u najmlađoj fazi razvoja sastojine (mladik)?",
    a: ["Čista sječa", "Njega mladika (čišćenje)", "Konačna sječa", "Krčenje panjeva"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'sastojinska smjesa' (mješovita sastojina)?",
    a: ["Sastojina sastavljena od dvije ili više vrsta drveća", "Sastojina samo jedne vrste", "Sastojina bez drveća", "Rasadnik"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koji je glavni razlog uzgoja mješovitih sastojina umjesto monokultura?",
    a: ["Manja otpornost na bolesti i štetnike", "Veća stabilnost, biodiverzitet i otpornost na štetnike/bolesti", "Brži rast svih vrsta podjednako", "Manji troškovi sječe"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'rasadnik' u šumarstvu?",
    a: ["Mjesto gdje se uzgajaju sadnice za pošumljavanje", "Skladište drvne građe", "Fabrika namještaja", "Šumska cesta"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta znači pojam 'sukcesija' u razvoju šumske vegetacije?",
    a: ["Nagli nestanak šume", "Postupna smjena biljnih zajednica tokom vremena do stabilne klimaks zajednice", "Sadnja u redovima", "Sječa u zimskom periodu"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Koja vrsta sječe se koristi kod postepenog (oplodnog) načina pomlađivanja?",
    a: ["Oplodna sječa u više etapa (pripremni, naplodni, dovršni sijek)", "Jedna potpuna sječa odjednom", "Sječa samo bolesnih stabala", "Sječa samo najstarijih stabala pojedinačno kroz stoljeće"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'podstojna etaža' u sastojini?",
    a: ["Sloj drveća/grmlja ispod glavnog (nadstojnog) sklopa krošanja", "Korijenov sistem", "Sloj tla", "Gornji dio krošnje najviših stabala"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Zašto se u uzgoju šuma vodi računa o 'sklopu' sastojine?",
    a: ["Sklop utiče na svjetlost, rast i konkurenciju među stablima", "Sklop određuje boju lišća", "Sklop nema uticaja na rast", "Sklop se odnosi samo na cijenu drveta"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koja je razlika između 'čiste' i 'mješovite' sastojine?",
    a: ["Nema razlike", "Čista sastojina ima jednu vrstu drveća, mješovita dvije ili više", "Čista sastojina je uvijek starija", "Mješovita sastojina nema podmladak"],
    correct: 1,
  },
  {
    category: "uzgajanje",
    q: "Šta je cilj 'njege sastojina' tokom cijelog uzgojnog ciklusa?",
    a: ["Poboljšanje kvaliteta, stabilnosti i prirasta sastojine", "Potpuno uništavanje slabijih stabala bez ikakvog plana", "Sprečavanje bilo kakvog rasta", "Povećanje broja štetočina"],
    correct: 0,
  },

  // ---------- EKONOMIKA ŠUMARSTVA ----------
  {
    category: "ekonomika",
    q: "Šta proučava ekonomika šumarstva?",
    a: ["Isključivo biologiju drveća", "Ekonomske zakonitosti proizvodnje, korištenja i vrednovanja šumskih resursa", "Geologiju tla", "Klimatske promjene"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Šta je 'vrijednost prirasta' u ekonomici šumarstva?",
    a: ["Tržišna vrijednost godišnjeg povećanja drvne mase", "Cijena sjekire", "Trošak transporta drveta", "Plaća šumskog radnika"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta obuhvata pojam 'troškovi proizvodnje' u šumarstvu?",
    a: ["Samo cijena sadnica", "Svi troškovi uzgoja, zaštite, sječe i transporta drveta", "Samo plaće menadžmenta", "Samo porezi"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Šta je 'renta' (zemljišna renta) u kontekstu šumskog zemljišta?",
    a: ["Prihod koji vlasnik ostvaruje od korištenja šumskog zemljišta", "Vrsta poreza na drvo", "Cijena sjekire", "Naknada za gašenje požara"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koje su glavne kategorije proizvoda šume koje se ekonomski vrednuju?",
    a: ["Samo drvna masa", "Drvni proizvodi i nedrvni proizvodi (plodovi, gljive, med, rekreacija i sl.)", "Samo sjeme", "Samo divljač"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Šta je 'eksterna vrijednost' (eksternalija) šume u ekonomskom smislu?",
    a: ["Vrijednost koja se ne prodaje direktno na tržištu (npr. čist zrak, zaštita voda, biodiverzitet)", "Cijena drveta na berzi", "Trošak sječe", "Plaća radnika"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je cilj analize troškova i koristi (cost-benefit analize) u šumarstvu?",
    a: ["Utvrđivanje boje drveta", "Procjena ekonomske opravdanosti šumarskih investicija/mjera", "Mjerenje visine stabla", "Klasifikacija tla"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Koji faktor NAJVIŠE utiče na tržišnu cijenu drvne građe?",
    a: ["Kvalitet, vrsta drveta i tržišna ponuda/potražnja", "Boja lišća u jesen", "Broj ptica u šumi", "Datum sječe u kalendaru"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'diskontna stopa' u ekonomskim proračunima dugoročnih šumarskih investicija?",
    a: ["Stopa kojom se buduće vrijednosti svode na sadašnju vrijednost", "Porez na drvo", "Cijena goriva", "Plaća šumara"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Zašto je dug proizvodni ciklus (ophodnja) poseban ekonomski izazov u šumarstvu?",
    a: ["Jer nema uticaja na investicije", "Jer kapital ostaje vezan dugi niz godina prije povrata investicije", "Jer se drvo brzo kvari", "Jer nema tržišta za drvo"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Šta predstavlja 'dodana vrijednost' u preradi drveta?",
    a: ["Razlika u vrijednosti sirovog drveta i gotovog proizvoda nakon prerade", "Cijena transporta", "Porez na promet", "Trošak sječe"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koji ekonomski princip podrazumijeva korištenje šume bez ugrožavanja budućih generacija?",
    a: ["Princip maksimalnog profita", "Princip održivosti (trajnosti)", "Princip monopola", "Princip nulte proizvodnje"],
    correct: 1,
  },
  {
    category: "ekonomika",
    q: "Šta je 'šumska renta' prema klasičnoj teoriji optimalne ophodnje (npr. Faustmannova formula)?",
    a: ["Optimalna ophodnja koja maksimizira sadašnju vrijednost budućih prihoda od šume", "Porez na sječu", "Plaća šumara", "Cijena goriva za mašine"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koji su glavni tržišni kanali prodaje drvne građe?",
    a: ["Direktna prodaja, aukcije/tenderi, ugovori sa prerađivačima", "Samo poklon", "Samo razmjena za hranu", "Samo izvoz bez domaće prodaje"],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Zašto certifikacija šuma (npr. FSC) može imati ekonomski značaj?",
    a: ["Nema nikakav ekonomski uticaj", "Omogućava pristup zahtjevnijim tržištima i višu cijenu proizvoda", "Povećava troškove bez ikakve koristi", "Zabranjuje prodaju drveta"],
    correct: 1,
  },

  // ---------- ISKORIŠTAVANJE ŠUMA ----------
  {
    category: "iskoristavanje",
    q: "Šta obuhvata predmet 'iskorištavanje šuma'?",
    a: ["Samo sadnju drveća", "Sječu, izradu, privlačenje i transport šumskih drvnih sortimenata", "Samo zaštitu od požara", "Samo mjerenje visine stabala"],
    correct: 1,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'sortiment' u iskorištavanju šuma?",
    a: ["Vrsta gljive", "Dio posječenog stabla obrađen prema namjeni i standardima (npr. trupac, celuloza)", "Alat za sječu", "Vrsta tla"],
    correct: 1,
  },
  {
    category: "iskoristavanje",
    q: "Koji alat se tradicionalno koristi za obaranje stabala?",
    a: ["Motorna pila", "Kosilica", "Bušilica", "Čekić"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'privlačenje drveta' (izvoz iz sastojine)?",
    a: ["Transport posječenog drveta od panja do pomoćnog stovarišta/kamionskog puta", "Sadnja drveća", "Mjerenje prečnika", "Zaštita od požara"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koja mašina se najčešće koristi za privlačenje (izvoz) drveta u brdovitim terenima?",
    a: ["Traktor s vitlom (šumski traktor)", "Kombajn za žito", "Bager za iskop kanala", "Viličar u skladištu"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'žičara' u kontekstu iskorištavanja šuma?",
    a: ["Sistem za transport drveta pomoću čeličnog užeta preko strmog/nepristupačnog terena", "Vrsta motorne pile", "Ograda oko rasadnika", "Alat za mjerenje visine"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'harvester' u savremenoj mehanizaciji sječe?",
    a: ["Mašina koja obara, kreše grane i kroji stablo u sortimente", "Vrsta sadnice", "Sistem navodnjavanja", "Vrsta gnojiva"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta znači 'forwarder' u iskorištavanju šuma?",
    a: ["Mašina za skupljanje i transport izrađenih sortimenata do stovarišta", "Vrsta motorne testere", "Vrsta drveta", "Alat za mjerenje debljine kore"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'stovarište drveta'?",
    a: ["Mjesto privremenog skladištenja i sortiranja posječenog drveta prije daljeg transporta", "Rasadnik sadnica", "Fabrika namještaja", "Šumska čistina bez drveća"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koja mjera sigurnosti je obavezna prilikom rada motornom pilom?",
    a: ["Lična zaštitna oprema (kaciga, štitnici, zaštitne hlače i sl.)", "Rad bez ikakve zaštite radi brzine", "Rad isključivo noću", "Izbjegavanje obuke"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'kresanje grana' (grananje)?",
    a: ["Uklanjanje grana sa posječenog debla", "Sadnja novih grana", "Mjerenje visine krošnje", "Zaštita debla od insekata"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta se podrazumijeva pod pojmom 'šumski put' u iskorištavanju šuma?",
    a: ["Cesta izgrađena radi pristupa sastojinama za sječu, njegu i transport", "Staza za pješake u parku", "Granica države", "Putanja migracije ptica"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koji faktor je najvažniji pri planiranju tehnologije sječe i privlačenja drveta?",
    a: ["Nagib terena, vrsta sastojine i zaštita preostalih stabala/tla", "Boja kamiona", "Broj radnika u kancelariji", "Cijena goriva u susjednoj državi"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'kalamitetna sječa'?",
    a: ["Redovna planirana sječa zrelih stabala", "Hitna sječa nakon prirodnih nepogoda (vjetroizvala, snijegolom, napad štetnika)", "Sječa u rasadniku", "Sječa isključivo ukrasnog drveća"],
    correct: 1,
  },
  {
    category: "iskoristavanje",
    q: "Zašto je važno minimizirati oštećenja tla i preostalih stabala prilikom iskorištavanja šuma?",
    a: ["Nije važno, šteta se ne prati", "Radi očuvanja produktivnosti staništa i zdravlja preostale sastojine", "Samo radi estetike", "Radi bržeg rasta korova"],
    correct: 1,
  },

  // ---------- DENDROMETRIJA ----------
  {
    category: "dendrometrija",
    q: "Šta proučava dendrometrija?",
    a: ["Mjerenje i procjenu dimenzija, zapremine i prirasta drveća i sastojina", "Isključivo bolesti drveća", "Ekonomiju šumarstva", "Zakone o šumama"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kojim instrumentom se mjeri prsni prečnik stabla (na 1,3 m visine)?",
    a: ["Šumarska klupa (precnjak)", "Barometar", "Termometar", "Kompas"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Na kojoj standardnoj visini se mjeri prsni prečnik (DBH)?",
    a: ["0,5 m", "1,3 m", "2,5 m", "5,0 m"],
    correct: 1,
  },
  {
    category: "dendrometrija",
    q: "Koji instrument se koristi za mjerenje visine stabla?",
    a: ["Visinomjer (hipsometar)", "Precnjak", "Buserol", "Vaga"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'temeljnica' (bazna površina) stabla?",
    a: ["Površina poprečnog presjeka debla na 1,3 m visine", "Površina krošnje", "Površina korijenovog sistema", "Površina lista"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kako se izračunava zapremina stabla u dendrometriji?",
    a: ["Direktnim mjerenjem ili pomoću tarifa/formula na osnovu prečnika i visine", "Procjenom po broju grana", "Mjerenjem boje kore", "Brojanjem listova"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta su 'godovi' (godišnji prstenovi) na presjeku debla?",
    a: ["Slojevi drveta nastali godišnjim prirastom, koji se koriste za određivanje starosti stabla", "Bolest drveta", "Vrsta kore", "Oštećenje od insekata"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Čime se mjeri starost stabla bez obaranja, uzimanjem uzorka iz debla?",
    a: ["Presslerovim svrdlom (borer)", "Precnjakom", "Visinomjerom", "Busolom"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'tarifa' (drvnogromadna tablica) u dendrometriji?",
    a: ["Tablica za procjenu zapremine stabla na osnovu prečnika i/ili visine", "Cjenovnik drvne građe", "Zakonski propis o sječi", "Karta šumskih puteva"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta predstavlja 'srednji prečnik' sastojine?",
    a: ["Prečnik stabla čija temeljnica odgovara prosječnoj temeljnici svih stabala", "Najveći prečnik u sastojini", "Najmanji prečnik u sastojini", "Zbir svih prečnika"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'tekući godišnji prirast'?",
    a: ["Povećanje zapremine/dimenzija stabla ili sastojine u jednoj godini", "Ukupna zapremina stabla", "Broj godova od sadnje", "Prosječna visina sastojine"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kojom metodom se procjenjuje zapremina drvne mase cijele sastojine na terenu (uz uzorkovanje)?",
    a: ["Metodom probnih (uzorkih) ploha", "Brojanjem lišća", "Mjerenjem samo jednog stabla", "Procjenom 'od oka' bez mjerenja"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'sklop krošanja' i kako se najčešće izražava?",
    a: ["Stepen prekrivenosti tla krošnjama, izražava se u procentima ili desetinama", "Broj vrsta drveća u sastojini", "Prosječna starost sastojine", "Boja lišća u jesen"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Koja veličina se dobija množenjem temeljnice, visine i obličnog broja stabla?",
    a: ["Zapremina (drvna masa) stabla", "Starost stabla", "Prirast korijena", "Površina lista"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Zašto je precizna dendrometrijska procjena važna za gospodarenje šumama?",
    a: ["Nije važna, dovoljna je procjena 'od oka'", "Osnova je za planiranje sječa, prihoda i održivog gospodarenja", "Koristi se samo u naučne svrhe bez praktične primjene", "Odnosi se isključivo na estetiku šume"],
    correct: 1,
  },
];
