const CATEGORIES = [
  { id: "uredjivanje", label: "Uređivanje šuma", icon: "🗺️" },
  { id: "uzgajanje", label: "Uzgajanje šuma", icon: "🌱" },
  { id: "ekonomika", label: "Ekonomika šumarstva", icon: "💰" },
  { id: "iskoristavanje", label: "Iskorištavanje šuma", icon: "🪓" },
  { id: "dendrometrija", label: "Dendrometrija", icon: "📏" },
  { id: "mix", label: "Mix (sve kategorije)", icon: "🔀" },
];

// Napomena: tačan odgovor je uvijek na indeksu 0 (a[correct]) — aplikacija
// pri svakom pokretanju kviza nasumično miješa redoslijed ponuđenih odgovora,
// pa redoslijed unosa ovdje ne utiče na to kako ih korisnik vidi.

const QUESTIONS = [
  // ---------- UREĐIVANJE ŠUMA ----------
  {
    category: "uredjivanje",
    q: "Šta je osnovni cilj uređivanja šuma?",
    a: [
      "Planiranje i regulisanje gospodarenja šumom radi trajnosti prinosa",
      "Evidentiranje vlasništva nad šumskim zemljištem",
      "Određivanje botaničke klasifikacije vrsta drveća",
      "Sprječavanje pristupa javnosti šumskim površinama",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Kako se naziva osnovni planski dokument za gospodarenje šumom na nivou gospodarske jedinice?",
    a: ["Šumskoprivredna osnova", "Katastarski operat", "Prostorni plan općine", "Elaborat o procjeni uticaja na okoliš"],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'gospodarska jedinica' u uređivanju šuma?",
    a: [
      "Teritorijalno-gospodarska cjelina za koju se izrađuje osnova gazdovanja",
      "Najmanja mjerna jedinica drvne mase (m³)",
      "Organizaciona jedinica šumarskog fakulteta",
      "Udruženje privatnih šumovlasnika",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta predstavlja 'etat' u šumarstvu?",
    a: [
      "Propisanu (dozvoljenu) količinu drvne mase za sječu u određenom periodu",
      "Prosječan godišnji prirast po hektaru",
      "Ukupnu zapreminu cijele sastojine",
      "Vremenski period trajanja ophodnje",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Koji je cilj podjele šume na odjele i odsjeke?",
    a: [
      "Lakše planiranje, evidencija i gospodarenje šumom",
      "Razgraničenje vlasništva između privatnih i državnih šuma",
      "Određivanje granica lovišta",
      "Raspodjela sastojina prema botaničkim porodicama",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'ophodnja' (turnus) u uređivanju šuma?",
    a: [
      "Vremenski period za koji se šuma pomladi i doraste do sječive zrelosti",
      "Vrijeme potrebno da sjeme proklija nakon sjetve",
      "Period mirovanja tla nakon sječe prije nove sadnje",
      "Godišnji ciklus radova njege mladika",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Koji faktor NAJVIŠE određuje dužinu ophodnje?",
    a: [
      "Vrsta drveta, stanište i cilj gospodarenja",
      "Broj radnika raspoloživih za sječu",
      "Udaljenost sastojine od šumske ceste",
      "Trenutna cijena drvne građe na tržištu",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'prirast' drvne mase?",
    a: [
      "Povećanje zapremine drvne mase u određenom vremenskom periodu",
      "Ukupna zapremina posječene drvne mase u jednoj godini",
      "Broj novozasađenih sadnica u rasadniku",
      "Postotak vlage u drvetu nakon sječe",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta znači princip 'trajnosti prinosa' u uređivanju šuma?",
    a: [
      "Ravnomjerno i održivo korištenje šume tako da prinos ostane trajno moguć",
      "Fiksnu cijenu drveta koja se ne mijenja tokom cijele ophodnje",
      "Obavezu sadnje iste vrste na cijeloj površini",
      "Zabranu sječe tokom prvih deset godina ophodnje",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je funkcija Geografskog informacionog sistema (GIS) u uređivanju šuma?",
    a: [
      "Prikupljanje, analiza i prikaz prostornih podataka o šumi",
      "Automatsko obaranje stabala putem satelitskog navođenja",
      "Mjerenje vlage tla na terenu",
      "Praćenje tržišne cijene drvnih sortimenata",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je 'bonitet staništa' u uređivanju šuma?",
    a: [
      "Ocjena proizvodne sposobnosti staništa za rast šume",
      "Klasifikacija drveta prema kvalitetu za tržište",
      "Procjena rizika od požara na određenoj lokaciji",
      "Ocjena estetske vrijednosti pejzaža",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Koji dokument definiše dugoročne ciljeve gospodarenja šumama na nivou cijele države/regije?",
    a: [
      "Strategija/plan razvoja šumarstva",
      "Šumskoprivredna osnova jedne gospodarske jedinice",
      "Godišnji plan sječa jedne šumarije",
      "Pravilnik o zaštiti na radu u šumarstvu",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta je zadatak revizije šumskoprivredne osnove?",
    a: [
      "Periodična provjera i usklađivanje plana gazdovanja sa stvarnim stanjem šume",
      "Prvo izdavanje osnove za novoosnovanu gospodarsku jedinicu",
      "Prodaja gospodarske jedinice novom vlasniku",
      "Godišnji obračun plaća šumarskog osoblja",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Šta znači pojam 'normalna šuma' u teoriji uređivanja šuma?",
    a: [
      "Teorijski model šume s idealnom razdiobom starosnih razreda za trajni prinos",
      "Šuma u kojoj prevladava samo jedna vrsta drveća",
      "Šuma bez ikakvih tragova bolesti ili štetnika",
      "Prosječna gustina stabala u nizinskim šumama",
    ],
    correct: 0,
  },
  {
    category: "uredjivanje",
    q: "Koja metoda uređivanja šuma se zasniva na kontroli stanja sastojine i prirasta umjesto strogog plana sječa?",
    a: [
      "Metoda kontrole (kontrolna metoda)",
      "Metoda čiste (jednokratne) sječe cijele sastojine",
      "Metoda normalne šume sa fiksnim etatom",
      "Metoda slobodnog (neplanskog) korištenja šume",
    ],
    correct: 0,
  },

  // ---------- UZGAJANJE ŠUMA ----------
  {
    category: "uzgajanje",
    q: "Šta je zadatak uzgajanja šuma kao struke?",
    a: [
      "Njega, obnova i unapređenje šumskih sastojina",
      "Planiranje i regulisanje sječa na nivou gospodarske jedinice",
      "Mjerenje i procjena zapremine drvne mase",
      "Prerada drvne sirovine u gotove proizvode",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'prirodno pomlađivanje' šume?",
    a: [
      "Obnova šume iz sjemena zrelih stabala bez sadnje",
      "Obnova šume sadnjom sadnica uzgojenih u rasadniku",
      "Obnova šume izbojcima iz panja nakon sječe",
      "Unošenje sjemena iz drugih klimatskih područja",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'vještačko pomlađivanje'?",
    a: [
      "Obnova šume sadnjom sadnica ili sjetvom sjemena od strane čovjeka",
      "Prirodno nicanje sjemenki palih sa majčinskih stabala",
      "Obnova iz izbojaka korijena nakon sječe",
      "Spontano naseljavanje pionirskih vrsta na čistini",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Kako se naziva obnova šume iz izbojaka iz panja ili korijena?",
    a: ["Panjača (izdanačka šuma)", "Sjemenjača (visoka šuma)", "Plantaža brzorastućih vrsta", "Zaštitna šuma"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je proreda (prorjeđivanje) sastojine?",
    a: [
      "Uklanjanje dijela stabala radi boljeg rasta preostalih i kvalitetnijeg drveta",
      "Potpuno uklanjanje svih stabala sa površine",
      "Sadnja dodatnih sadnica u praznine sklopa",
      "Krčenje panjeva nakon konačne sječe",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koja mjera njege se provodi u najmlađoj fazi razvoja sastojine (mladik)?",
    a: ["Njega mladika (čišćenje)", "Oplodna (dovršna) sječa", "Proreda odrasle sastojine", "Sanitarna sječa bolesnih stabala"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'sastojinska smjesa' (mješovita sastojina)?",
    a: [
      "Sastojina sastavljena od dvije ili više vrsta drveća",
      "Sastojina nastala iz izbojaka panja",
      "Sastojina jednake starosti svih stabala",
      "Sastojina u fazi pripremne sječe",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koji je glavni razlog uzgoja mješovitih sastojina umjesto monokultura?",
    a: [
      "Veća stabilnost, biodiverzitet i otpornost na štetnike/bolesti",
      "Jednostavnije planiranje sječa i manje administracije",
      "Brži i ujednačeniji rast svih vrsta",
      "Niži troškovi sadnje i njege",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'rasadnik' u šumarstvu?",
    a: [
      "Mjesto gdje se uzgajaju sadnice za pošumljavanje",
      "Dio sastojine ostavljen za prirodno pomlađivanje",
      "Skladište sjemena prije prodaje",
      "Ograđena površina za zaštitu od divljači",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta znači pojam 'sukcesija' u razvoju šumske vegetacije?",
    a: [
      "Postupna smjena biljnih zajednica tokom vremena do stabilne klimaks zajednice",
      "Nagli nestanak šume usljed kalamiteta",
      "Godišnji ciklus listanja i opadanja lišća",
      "Vertikalna raspodjela etaža unutar jedne sastojine",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koja vrsta sječe se koristi kod postepenog (oplodnog) načina pomlađivanja?",
    a: [
      "Oplodna sječa u više etapa (pripremni, naplodni, dovršni sijek)",
      "Čista sječa cijele sastojine odjednom",
      "Sječa pojedinačnih stabala kroz cijelu ophodnju (prebirna)",
      "Sanitarna sječa nakon kalamiteta",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je 'podstojna etaža' u sastojini?",
    a: [
      "Sloj drveća/grmlja ispod glavnog (nadstojnog) sklopa krošanja",
      "Korijenov sistem najstarijih stabala",
      "Gornji, najosvjetljeniji dio krošnje",
      "Sloj humusa na površini tla",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Zašto se u uzgoju šuma vodi računa o 'sklopu' sastojine?",
    a: [
      "Sklop utiče na svjetlost, rast i konkurenciju među stablima",
      "Sklop određuje granicu gospodarske jedinice",
      "Sklop je zakonski propisan postotak sječe",
      "Sklop pokazuje starost sastojine u godinama",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koja je razlika između 'čiste' i 'mješovite' sastojine?",
    a: [
      "Čista sastojina ima jednu vrstu drveća, mješovita dvije ili više",
      "Čista sastojina je uvijek nastala vještačkim pomlađivanjem",
      "Mješovita sastojina nema podstojnu etažu",
      "Čista sastojina nema mogućnost prirodnog pomlađivanja",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Šta je cilj 'njege sastojina' tokom cijelog uzgojnog ciklusa?",
    a: [
      "Poboljšanje kvaliteta, stabilnosti i prirasta sastojine",
      "Smanjenje ukupnog broja vrsta na minimum",
      "Ubrzavanje trenutka konačne (dovršne) sječe",
      "Potpuno isključivanje prirodnog pomlađivanja",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koji kriterij je osnova Kraftove klasifikacije socijalnog položaja stabala u sastojini?",
    a: [
      "Socijalni položaj stabla određen razvijenošću krošnje i visinom u odnosu na susjedna stabla",
      "Starost stabla utvrđena brojanjem godova",
      "Prečnik stabla izmjeren precnjakom na 1,3 m",
      "Botanička pripadnost stabla određenoj vrsti",
    ],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Prema Kraftovoj klasifikaciji, koja klasa obuhvata potpuno vladajuća (predominantna) stabla najrazvijenije krošnje?",
    a: ["I klasa", "II klasa", "III klasa", "IV klasa"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Koja Kraftova klasa obuhvata suvladajuća stabla čije krošnje još učestvuju u glavnom sklopu, ali su manje razvijena od vladajućih?",
    a: ["III klasa", "I klasa", "II klasa", "V klasa"],
    correct: 0,
  },
  {
    category: "uzgajanje",
    q: "Stabla V Kraftove klase (zaostala/potisnuta) prilikom proreda se u pravilu:",
    a: [
      "Uklanjaju, jer zbog zaostajanja u rastu ne mogu preuzeti dominantnu ulogu u sklopu",
      "Ostavljaju kao buduća nosioca prirasta sastojine",
      "Koriste kao sjemenska stabla za prirodno pomlađivanje",
      "Proglašavaju zaštićenim stablima bez obzira na vrstu",
    ],
    correct: 0,
  },

  // ---------- EKONOMIKA ŠUMARSTVA ----------
  {
    category: "ekonomika",
    q: "Šta proučava ekonomika šumarstva?",
    a: [
      "Ekonomske zakonitosti proizvodnje, korištenja i vrednovanja šumskih resursa",
      "Biološke procese rasta i razvoja drveća",
      "Mjerenje dimenzija i zapremine stabala",
      "Tehnologiju sječe i privlačenja drveta",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'vrijednost prirasta' u ekonomici šumarstva?",
    a: [
      "Tržišna vrijednost godišnjeg povećanja drvne mase",
      "Ukupna vrijednost cijele sastojine na dan procjene",
      "Trošak uzgoja jednog hektara šume",
      "Prosječna cijena rada šumskog radnika",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta obuhvata pojam 'troškovi proizvodnje' u šumarstvu?",
    a: [
      "Svi troškovi uzgoja, zaštite, sječe i transporta drveta",
      "Samo trošak sadnog materijala",
      "Isključivo poreze i dažbine na promet drveta",
      "Trošak administracije bez terenskih radova",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'renta' (zemljišna renta) u kontekstu šumskog zemljišta?",
    a: [
      "Prihod koji vlasnik ostvaruje od korištenja šumskog zemljišta",
      "Zakonski propisan porez na svaku sječu",
      "Naknada državi za pravo gospodarenja državnom šumom",
      "Trošak osiguranja šume od požara",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koje su glavne kategorije proizvoda šume koje se ekonomski vrednuju?",
    a: [
      "Drvni proizvodi i nedrvni proizvodi (plodovi, gljive, med, rekreacija i sl.)",
      "Isključivo trupci namijenjeni izvozu",
      "Samo proizvodi prerađeni u finalne proizvode",
      "Isključivo prihodi od turizma u šumi",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'eksterna vrijednost' (eksternalija) šume u ekonomskom smislu?",
    a: [
      "Vrijednost koja se ne prodaje direktno na tržištu (npr. čist zrak, zaštita voda, biodiverzitet)",
      "Vrijednost drveta izvezenog na strano tržište",
      "Procijenjena vrijednost šume u knjigovodstvu preduzeća",
      "Dio prihoda ostvaren izvan gospodarske jedinice",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je cilj analize troškova i koristi (cost-benefit analize) u šumarstvu?",
    a: [
      "Procjena ekonomske opravdanosti šumarskih investicija/mjera",
      "Određivanje botaničke vrijednosti sastojine",
      "Mjerenje ekološkog otiska sječe",
      "Propisivanje visine etata za narednu godinu",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koji faktor NAJVIŠE utiče na tržišnu cijenu drvne građe?",
    a: [
      "Kvalitet, vrsta drveta i tržišna ponuda/potražnja",
      "Nadmorska visina na kojoj je stablo raslo",
      "Dužina ophodnje propisana osnovom",
      "Broj godova vidljivih na panju",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'diskontna stopa' u ekonomskim proračunima dugoročnih šumarskih investicija?",
    a: [
      "Stopa kojom se buduće vrijednosti svode na sadašnju vrijednost",
      "Porezna stopa na promet drvne građe",
      "Kamatna stopa kredita za kupovinu mehanizacije",
      "Postotak gubitka drvne mase pri preradi",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Zašto je dug proizvodni ciklus (ophodnja) poseban ekonomski izazov u šumarstvu?",
    a: [
      "Jer kapital ostaje vezan dugi niz godina prije povrata investicije",
      "Jer se cijena drveta ne mijenja tokom cijele ophodnje",
      "Jer se troškovi uzgoja ne mogu unaprijed procijeniti",
      "Jer zakon zabranjuje prodaju mlade šume",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta predstavlja 'dodana vrijednost' u preradi drveta?",
    a: [
      "Razlika u vrijednosti sirovog drveta i gotovog proizvoda nakon prerade",
      "Ukupna vrijednost izvezenog drveta",
      "Porez plaćen prilikom prodaje sortimenata",
      "Trošak transporta od stovarišta do fabrike",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koji ekonomski princip podrazumijeva korištenje šume bez ugrožavanja budućih generacija?",
    a: [
      "Princip održivosti (trajnosti)",
      "Princip maksimalne trenutne dobiti",
      "Princip slobodnog tržišta bez regulacije",
      "Princip jednake raspodjele etata svim vlasnicima",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta je 'šumska renta' prema klasičnoj teoriji optimalne ophodnje (npr. Faustmannova formula)?",
    a: [
      "Optimalna ophodnja koja maksimizira sadašnju vrijednost budućih prihoda od šume",
      "Fiksni godišnji porez koji vlasnik plaća državi",
      "Prosječna cijena drveta na regionalnom tržištu",
      "Naknada za korištenje šumskog puta",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Koji su glavni tržišni kanali prodaje drvne građe?",
    a: [
      "Direktna prodaja, aukcije/tenderi, ugovori sa prerađivačima",
      "Isključivo državni monopol na otkup",
      "Razmjena drveta za druge poljoprivredne proizvode",
      "Prodaja isključivo krajnjim potrošačima u maloprodaji",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Zašto certifikacija šuma (npr. FSC) može imati ekonomski značaj?",
    a: [
      "Omogućava pristup zahtjevnijim tržištima i višu cijenu proizvoda",
      "Oslobađa vlasnika plaćanja svih poreza",
      "Garantuje državnu subvenciju bez obzira na kvalitet",
      "Ukida potrebu za šumskoprivrednom osnovom",
    ],
    correct: 0,
  },
  {
    category: "ekonomika",
    q: "Šta pokazuje neto sadašnja vrijednost (NPV) šumarske investicije kada je pozitivna?",
    a: [
      "Da diskontovani prihodi premašuju diskontovane troškove uz zadatu diskontnu stopu — investicija je ekonomski opravdana",
      "Da investicija nema nikakav rizik",
      "Da se ophodnja mora skratiti na polovinu",
      "Da je tržišna cijena drveta fiksna do kraja ophodnje",
    ],
    correct: 0,
  },

  // ---------- ISKORIŠTAVANJE ŠUMA ----------
  {
    category: "iskoristavanje",
    q: "Šta obuhvata predmet 'iskorištavanje šuma'?",
    a: [
      "Sječu, izradu, privlačenje i transport šumskih drvnih sortimenata",
      "Planiranje sječa na nivou gospodarske jedinice",
      "Njegu i obnovu šumskih sastojina",
      "Mjerenje zapremine stojećih stabala",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'sortiment' u iskorištavanju šuma?",
    a: [
      "Dio posječenog stabla obrađen prema namjeni i standardima (npr. trupac, celuloza)",
      "Vrsta mašine za privlačenje drveta",
      "Dokument koji prati transport drveta",
      "Skup pitanja klasifikovanih po vrsti sječe",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koji alat se tradicionalno koristi za obaranje stabala?",
    a: ["Motorna pila", "Šumarska klupa (precnjak)", "Presslerovo svrdlo", "Visinomjer (hipsometar)"],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'privlačenje drveta' (izvoz iz sastojine)?",
    a: [
      "Transport posječenog drveta od panja do pomoćnog stovarišta/kamionskog puta",
      "Transport gotovih sortimenata od stovarišta do fabrike",
      "Sadnja sadnica na mjestu posječenih stabala",
      "Kresanje grana sa oborenog stabla",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koja mašina se najčešće koristi za privlačenje (izvoz) drveta u brdovitim terenima?",
    a: [
      "Traktor s vitlom (šumski traktor)",
      "Harvester s glavom za kresanje",
      "Forwarder za transport sortimenata",
      "Bager za izradu šumskih puteva",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'žičara' u kontekstu iskorištavanja šuma?",
    a: [
      "Sistem za transport drveta pomoću čeličnog užeta preko strmog/nepristupačnog terena",
      "Mašina koja obara i kroji stabla u sortimente",
      "Vozilo za prijevoz radnika do sječišta",
      "Uređaj za mjerenje nagiba terena",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'harvester' u savremenoj mehanizaciji sječe?",
    a: [
      "Mašina koja obara, kreše grane i kroji stablo u sortimente",
      "Mašina koja samo skuplja i transportuje već izrađene sortimente",
      "Sistem žičare za nepristupačan teren",
      "Uređaj za sadnju sadnica u rasadniku",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta znači 'forwarder' u iskorištavanju šuma?",
    a: [
      "Mašina za skupljanje i transport izrađenih sortimenata do stovarišta",
      "Mašina koja obara i kroji stabla (harvester)",
      "Traktor koji vuče stabla pomoću sajle (skidder)",
      "Motorna pila veće snage za deblje stablo",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'stovarište drveta'?",
    a: [
      "Mjesto privremenog skladištenja i sortiranja posječenog drveta prije daljeg transporta",
      "Mjesto gdje se uzgajaju sadnice za pošumljavanje",
      "Dio sastojine određen za sanitarnu sječu",
      "Skladište rezervnih dijelova za mehanizaciju",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koja mjera sigurnosti je obavezna prilikom rada motornom pilom?",
    a: [
      "Lična zaštitna oprema (kaciga, štitnici, zaštitne hlače i sl.)",
      "Prisustvo najmanje dvoje radnika na svakom stablu",
      "Rad isključivo u jutarnjim satima",
      "Prethodna dozvola lokalne zajednice za svako stablo",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'kresanje grana' (grananje)?",
    a: [
      "Uklanjanje grana sa posječenog debla",
      "Uklanjanje suvih grana sa živog stabla radi njege",
      "Rezanje debla na sortimente propisane dužine",
      "Uklanjanje kore prije transporta",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta se podrazumijeva pod pojmom 'šumski put' u iskorištavanju šuma?",
    a: [
      "Cesta izgrađena radi pristupa sastojinama za sječu, njegu i transport",
      "Staza obilježena za edukativne posjete šumi",
      "Granica između dvije gospodarske jedinice",
      "Trasa žičare za transport drveta",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koji faktor je najvažniji pri planiranju tehnologije sječe i privlačenja drveta?",
    a: [
      "Nagib terena, vrsta sastojine i zaštita preostalih stabala/tla",
      "Trenutna tržišna cijena goriva",
      "Broj radnika zaposlenih u upravi šumarije",
      "Udaljenost sjedišta šumarije od glavnog grada",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta je 'kalamitetna sječa'?",
    a: [
      "Hitna sječa nakon prirodnih nepogoda (vjetroizvala, snijegolom, napad štetnika)",
      "Redovna planirana sječa zrelih stabala prema etatu",
      "Sječa u sklopu njege mladika",
      "Sječa isključivo u rasadniku radi proreda sadnica",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Zašto je važno minimizirati oštećenja tla i preostalih stabala prilikom iskorištavanja šuma?",
    a: [
      "Radi očuvanja produktivnosti staništa i zdravlja preostale sastojine",
      "Radi ispunjavanja estetskih zahtjeva turista",
      "Radi smanjenja količine papirologije nakon sječe",
      "Radi bržeg isplaćivanja radnika po učinku",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Šta podrazumijeva 'klasiranje' (kvalitativna klasifikacija) trupaca u iskorištavanju šuma?",
    a: [
      "Razvrstavanje trupaca u klase kvaliteta prema greškama drveta, ravnosti debla i dimenzijama",
      "Razvrstavanje stabala prema botaničkoj vrsti prije sječe",
      "Raspoređivanje radnika u sječne grupe prema iskustvu",
      "Utvrđivanje redoslijeda sječe stabala u sastojini",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Kojim oznakama se u evropskim standardima klasiranja oblog drveta (npr. za hrast i bukvu) obično izražavaju klase kvaliteta trupaca, od najviše ka nižoj?",
    a: [
      "L (izuzetna klasa), A, B, C, D",
      "1, 2, 3, 4, 5 redom bez posebnih oznaka kvaliteta",
      "Alfa, beta, gama, delta",
      "Premium, standard, ekonomik",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Koji faktori NAJVIŠE određuju klasu kvaliteta trupca prilikom klasiranja?",
    a: [
      "Ravnost debla, prisustvo grešaka (kvrge, trulež, krivina) i dimenzije (prečnik, dužina)",
      "Nadmorska visina na kojoj je stablo raslo",
      "Datum sječe u kalendarskoj godini",
      "Udaljenost stovarišta od fabrike",
    ],
    correct: 0,
  },
  {
    category: "iskoristavanje",
    q: "Zašto je klasiranje oblog drveta ekonomski važno?",
    a: [
      "Viša klasa kvaliteta direktno određuje višu tržišnu cijenu sortimenta",
      "Klasa kvaliteta utiče isključivo na težinu trupca",
      "Klasiranje je potrebno samo za izvozne pošiljke",
      "Klasa kvaliteta ne utiče na cijenu, samo na evidenciju",
    ],
    correct: 0,
  },

  // ---------- DENDROMETRIJA ----------
  {
    category: "dendrometrija",
    q: "Šta proučava dendrometrija?",
    a: [
      "Mjerenje i procjenu dimenzija, zapremine i prirasta drveća i sastojina",
      "Proučavanje bolesti i štetnika drveća",
      "Planiranje sječa na nivou gospodarske jedinice",
      "Ekonomsko vrednovanje šumskih proizvoda",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kojim instrumentom se mjeri prsni prečnik stabla (na 1,3 m visine)?",
    a: ["Šumarska klupa (precnjak)", "Visinomjer (hipsometar)", "Presslerovo svrdlo", "Buserol (šumarska busola)"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Na kojoj standardnoj visini se mjeri prsni prečnik (DBH)?",
    a: ["1,3 m", "0,5 m", "2,0 m", "3,0 m"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Koji instrument se koristi za mjerenje visine stabla?",
    a: ["Visinomjer (hipsometar)", "Šumarska klupa (precnjak)", "Presslerovo svrdlo", "Tarifna tablica"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'temeljnica' (bazna površina) stabla?",
    a: [
      "Površina poprečnog presjeka debla na 1,3 m visine",
      "Ukupna površina krošnje stabla",
      "Površina koju zauzima korijenov sistem",
      "Površina tla ispod jednog stabla u sastojini",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kako se izračunava zapremina stabla u dendrometriji?",
    a: [
      "Direktnim mjerenjem ili pomoću tarifa/formula na osnovu prečnika i visine",
      "Brojanjem godova na panju nakon sječe",
      "Procjenom na osnovu širine krošnje",
      "Mjerenjem težine posječenog debla",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta su 'godovi' (godišnji prstenovi) na presjeku debla?",
    a: [
      "Slojevi drveta nastali godišnjim prirastom, koji se koriste za određivanje starosti stabla",
      "Oštećenja nastala napadom potkornjaka",
      "Granica između bjeljike i srži drveta",
      "Tragovi prethodnih sječa u sastojini",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Čime se mjeri starost stabla bez obaranja, uzimanjem uzorka iz debla?",
    a: ["Presslerovim svrdlom (borer)", "Šumarskom klupom (precnjakom)", "Visinomjerom (hipsometrom)", "Relaskopom"],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'tarifa' (drvnogromadna tablica) u dendrometriji?",
    a: [
      "Tablica za procjenu zapremine stabla na osnovu prečnika i/ili visine",
      "Cjenovnik drvne građe po sortimentima",
      "Zakonski propis o dozvoljenom obimu sječe",
      "Karta rasporeda šumskih puteva",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta predstavlja 'srednji prečnik' sastojine?",
    a: [
      "Prečnik stabla čija temeljnica odgovara prosječnoj temeljnici svih stabala",
      "Aritmetička sredina najvećeg i najmanjeg prečnika u sastojini",
      "Prečnik najzastupljenijeg stabla po broju primjeraka",
      "Prečnik stabla najbliže centru sastojine",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'tekući godišnji prirast'?",
    a: [
      "Povećanje zapremine/dimenzija stabla ili sastojine u jednoj godini",
      "Prosječan godišnji prirast tokom cijele ophodnje",
      "Ukupna zapremina sastojine na kraju ophodnje",
      "Broj novih stabala niklih tokom godine",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Kojom metodom se procjenjuje zapremina drvne mase cijele sastojine na terenu (uz uzorkovanje)?",
    a: [
      "Metodom probnih (uzorkih) ploha",
      "Mjerenjem svakog pojedinačnog stabla u sastojini",
      "Procjenom na osnovu satelitskih snimaka bez terenske provjere",
      "Množenjem površine sastojine sa prosječnom visinom stabala",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta je 'sklop krošanja' i kako se najčešće izražava?",
    a: [
      "Stepen prekrivenosti tla krošnjama, izražava se u procentima ili desetinama",
      "Prosječna udaljenost između susjednih stabala u metrima",
      "Ukupan broj vrsta drveća u sastojini",
      "Odnos visine i prečnika prosječnog stabla",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Koja veličina se dobija množenjem temeljnice, visine i obličnog broja stabla?",
    a: [
      "Zapremina (drvna masa) stabla",
      "Tekući godišnji prirast stabla",
      "Starost stabla u godinama",
      "Bonitet staništa na kojem stablo raste",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Zašto je precizna dendrometrijska procjena važna za gospodarenje šumama?",
    a: [
      "Osnova je za planiranje sječa, prihoda i održivog gospodarenja",
      "Koristi se isključivo u akademske i istraživačke svrhe",
      "Zakonski je obavezna samo za državne šume",
      "Potrebna je samo prilikom prodaje cijele gospodarske jedinice",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Koja formula za kubiciranje debla odgovara Huberovoj (metodi srednjeg presjeka)?",
    a: [
      "V = g(sredina) × L — temeljnica na polovini dužine pomnožena dužinom",
      "V = (g1 + g2)/2 × L — prosjek temeljnica krajnjih presjeka pomnožen dužinom",
      "V = L/6 × (g1 + 4×g(sredina) + g2) — Newtonova formula",
      "V = π × r² × h/3 — formula za zapreminu stošca",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Čemu služi Reinekeov indeks gustine sastojine (SDI)?",
    a: [
      "Standardizovanoj procjeni gustine sastojine nezavisnoj od prosječnog prečnika, radi poređenja različitih sastojina",
      "Određivanju botaničke vrste dominantnog stabla",
      "Izračunu tržišne cijene drvne mase",
      "Mjerenju vlažnosti drveta prije sušenja",
    ],
    correct: 0,
  },
  {
    category: "dendrometrija",
    q: "Šta predstavlja 'oblični broj' (formzahl) stabla u dendrometriji?",
    a: [
      "Odnos stvarne zapremine debla i zapremine cilindra iste temeljnice i visine — mjera odstupanja oblika debla od cilindra",
      "Broj godova izbrojan na panju nakon sječe",
      "Odnos visine i prečnika krošnje stabla",
      "Prosječan broj sortimenata dobijenih iz jednog stabla",
    ],
    correct: 0,
  },
];
